version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - db-network

  db:
    image: "postgres:15"
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - .docker/data/db:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
