#!/bin/sh

# Run Laravel Pint
# This script will run Laravel Pint on newly staged PHP Files.

files=$(git diff --cached --name-only --diff-filter=AMCR | grep "\.php$")
if echo "$files" | grep --quiet "\.php$"; then
    echo "Running Laravel Pint..."
    if composer pint-fix; then
        echo "Run with composer pint"
    else
        echo "Run with docker composer pint"
        docker compose exec -T app composer pint-fix $files || true
    fi
    echo "Add files"
    git add $files
fi
